name: server1
type: "java:8"

disk: 1024
hooks:
    build: mvn -DskipTests clean package kumuluzee:repackage -f source/pom.xml

mounts:
    '/app':
        source: local
        source_path: app_source

web:
    commands:
        start: |
           mv source/target/microprofile.jar app/microprofile.jar
           java -jar -Xmx512m -Dkumuluzee.server.http.port=$PORT app/microprofile.jar