  "https://{default}/server1":
  type: upstream
  upstream: "server1:http"

  "https://{default}/server2":
  type: upstream
  upstream: "server2:http"

 "https://{default}/":
  type: upstream
  upstream: "server1:http" 

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"