# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
  type: upstream
  upstream: "varnish:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://{default}/a":
  type: upstream
  upstream: "server1:http"

"https://www.{default}/a":
  type: redirect
  to: "https://{default}/a"

"https://{default}/b":
  type: upstream
  upstream: "server2:http"

"https://www.{default}/b":
  type: redirect
  to: "https://{default}/"             