# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
  type: upstream
  upstream: "server1:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://{default}/server1":
  type: upstream
  upstream: "server1:http" 

"https://www.{default}/server1":
  type: redirect
  to: "https://{default}/server1"  
  
"https://{default}/server2":
  type: upstream
  upstream: "server2:http"

"https://www.{default}/server2":
  type: redirect
  to: "https://{default}/server2"       