# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/server1":
    id: server1
    type: upstream
    upstream: "server1:http"

"https://{default}/server2":
    id: server2
    type: upstream
    upstream: "server2:http"